# ONLY TO RUN LOCAL DYNAMODB VALIDATIONS (NOT FOR THE COMPLETE APP)

version: '3.8'
services:
  dynamodb-local-tests:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local-tests
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  # cli-commands:
  #   depends_on:
  #     - dynamodb-local-tests
  #   image: amazon/aws-cli
  #   container_name: cli-commands
  #   ports:
  #   - "8080:8080"
  #   environment:
  #     AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
  #     AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
  #   command: >
  #     dynamodb list-tables --endpoint-url http://dynamodb-local:8000 --region us-east-1

