// Load VITE_BACKEND_API_URL from globalVars.json
const GLOBAL_VARS = {
  VITE_APP_USER_POOL_ID: "REPLACE_ME_FOR_USER_POOL_ID",
  VITE_APP_CLIENT_ID: "REPLACE_ME_FOR_CLIENT_ID",
  VITE_BACKEND_API_URL: "REPLACE_ME_FOR_BACKEND_API_URL",
  VITE_COGNITO_HOSTED_UI_ENDPOINT: "REPLACE_ME_FOR_COGNITO_HOSTED_UI_ENDPOINT",
};
export default GLOBAL_VARS;
